version: '3.8'
services:
  backend:
    build: ./backend
    command: ["sh", "-c", "python manage.py runserver 0.0.0.0:8000 --noreload"]
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    command: ["sh", "-c", "npm run dev -- --host 0.0.0.0"]
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - ./frontend:/app