# Generated by Django 5.2.6 on 2025-09-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='password_hash',
            new_name='password',
        ),
    ]
